version: "3.9"

services:
    postgres:
        image: postgres:latest
        container_name: postgres_container
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: dba
            POSTGRES_PASSWORD: ${SA_PASSWORD}
            POSTGRES_DB: db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        
        
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq_container
        ports:
            - "5672:5672"
            - "15672:15672"
        
    api:
        build: ./backend
        container_name: api_container
        ports:
            - "5223:5223"
        environment:
            ConnectionStrings__DefaultConnection: "User ID=dba;Password=${SA_PASSWORD};Host=postgres;Port=5432;Database=db;Pooling=true;Connection Lifetime=0;"
            RABBITMQ_HOST: rabbitmq
            ASPNETCORE_ENVIRONMENT: Development
            Jwt__Key: dW7Dp8OjbyBwcm9mw6l0aWNhIGNodXJjaA==
        restart: on-failure
        
volumes:
  postgres_data: